
libvirt_networks:
- network_name: mgmt
  network_type: nat_network_dhcp
  network_interface_address: 10.0.0.0/24
  network_dhcp_range_start: 10.0.0.100
  network_dhcp_range_stop: 10.0.0.254

- network_name: ocp
  network_type: nat_network_dhcp
  network_interface_address: 192.168.132.1
  network_dhcp_range_start: 192.168.132.2
  network_dhcp_range_stop: 192.168.132.254
