---

- block:
  - name: start the mdadm sync (max)
    shell: echo 300000 > /proc/sys/dev/raid/speed_limit_max
  
  - name: start the mdadm sync (min)
    shell: echo 50000 > /proc/sys/dev/raid/speed_limit_min
  when: start_sync | default(false)

- block: 
  - name: temporarily pause the mdadm sync (max)
    shell: 'echo 0 > /proc/sys/dev/raid/speed_limit_max'
  
  - name: temporarily pause the mdadm sync (min)
    shell: 'echo 0 > /proc/sys/dev/raid/speed_limit_min'
  when: stop_sync | default(false)
