---
# task list is run as a loop
# expects a network dictionary which it gets from the main.yml
# 
# Define the network using the jinja template
# open up any ports that are needed by looping the port list

- name: "Defining network {{ network.network_name }}"
  virt_net:
    command: define
    name: "{{ network.network_name }}"
    xml: '{{ lookup("template", "{{ item.network_type }}.xml.j2") }}'

- name: "Enable and Autostart virtual network {{ network.network_name }}"
  virt_net:
    state: active
    autostart: yes
    name: "{{ item.network_name }}"

# WIP
# loop over the network['fw'] list and run the firewall role.
# each item should contain a firewall config according to the firewall role
#- name: Configure firewall for network
#  include_role:
#    name: fw
#  loop: "{{ network.ports }}" 
#  loop_var: port
