- name: list all vms in group vms
  debug:
    msg: "{{ groups['vms'] }}"

- name: create VM 
  debug:
    msg: "{{ hostvars[host] }}"
  loop: "{{ groups['vms'] }}"
  loop_control:
    loop_var: host

- name: create VM 
  include_role:
    name: vm-create
  vars:
    vm: "{{ hostvars[host] }}"
  loop: "{{ groups['vms'] }}"
  loop_control:
    loop_var: host
