- name: get certs
  shell: "ls /etc/pki/entitlement/*  | grep -v '\\-key.pem'"
  register: certs

- name: set_fact certs
  set_fact:
    cdn_certs: "{{ certs.stdout_lines }}"

- name: get keys
  shell: "ls /etc/pki/entitlement/*  | grep  '\\-key.pem'"
  register: cdn_keys

- name: set_fact
  set_fact:
    cdn_keys: "{{ cdn_keys.stdout_lines }}"

- name: cert and key
  set_fact:
    cert: "{{ cdn_certs[0] }}"
    key: "{{ cdn_keys[0] }}"

- name: configure repo
  template:
    src: rhel.repo.j2
    dest: /etc/yum.repos.d/rhel.repo
