- hosts: labhost
  user: root
  gather_facts: true
  roles:
  - role: mdadm-sync
    vars: 
      stop_sync: true 
  - users
  - openvpn
  - libvirt
  - libvirt_network 
  - iptables
  - knockd
  - role: mdadm-sync
    vars: 
      start_sync: true 
