- set_fact:
    alphabet: ['a','b','c','d','e','f','g','h']

- name: get current blockdevice names
  shell: "virsh domblkinfo {{ vm.name }} --all | tail -n +3 | head -n -1 | awk '{ print $1 }'"
  register: blkdevs

- set_fact:
    dev_list: "{{ blkdevs.stdout_lines }}"


- name: pickout the /dev string and save for later
  set_fact:
    dev_string: "{{ dev_list[0][:-1] }}"

- name: remove the /dev part from list
  set_fact:
    comparison_list: "{{ dev_list | map('regex_replace', dev_string, '') | list }}"

- name: differ the two lists
  set_fact:
    usable_list: "{{ alphabet | difference(comparison_list) }}"

- name: whats the dev_name gonna be
  set_fact:
    dev_name: "{{dev_string }}{{ usable_list[0]}}"

- name: append dev_name to image name
  set_fact:
    image_name: "{{ vm.name }}_{{ dev_name }}"
  when: disk.name is not defined | default(false)

- name: append disk.name and dev_name to image name
  set_fact:
    image_name: "{{ vm.name }}_{{ disk.name }}_{{ dev_name }}"
  when: disk.name is defined | default(false)

- name: create disk
  command: qemu-img create -f qcow2 /var/lib/libvirt/images/{{ image_name }}.qcow2 {{ disk.size }} -o preallocation=metadata

- name: set perms
  file:
    path: /var/lib/libvirt/images/{{ image_name }}.qcow2
    owner: qemu
    group: qemu

- name: attach disk
  command: virsh attach-disk {{ vm.name }} --source /var/lib/libvirt/images/{{ image_name }}.qcow2 --target {{ dev_name}} --persistent --targetbus virtio --driver qemu --sourcetype file --subdriver qcow2
