- hosts: labhost
  become: true
  tasks:
  - include_role: 
      name: vm-create
    vars:
      vm:
        name: test
        network: mgmt

  - include_role: 
      name: vm-create
    vars:
      vm:
        name: test-extradisk
        network: mgmt
        extra_disks:
        - size: 25G
        - size: 35G

  - include_role: 
      name: vm-create
    vars:
      vm:
        name: satellite
        network: mgmt
        extra_disks:
        - size: 150G
          name: pulp
        - size: 20G
          name: mongo
        - size: 20G
          name: postgres

          
        
