- name: define virtual networks
  virt_net:
    command: define
    name: "{{ item.network_name }}"
    xml: '{{ lookup("template", "{{ item.network_type }}.xml.j2") }}'
  with_items:
    - "{{ libvirt_networks }}"

- name: enable and autostart virtual networks
  virt_net:
    state: active
    autostart: yes
    name: "{{ item.network_name }}"
  with_items:
    - "{{ libvirt_networks }}"

- name: reject internet access for internal network
  iptables:
    action: insert
    chain: FORWARD
    source: 172.16.3.0/24
    jump: REJECT
  register: block_internal_internet

- name: except infra services
  iptables:
    action: insert
    chain: FORWARD
    source: 172.16.3.0/24
    destination: 192.168.190.0/24
    jump: ACCEPT
  register: allow_internal

- name: except vpn
  iptables:
    action: insert
    chain: FORWARD
    source: 172.16.3.0/24
    destination: 192.168.201.0/24
    jump: ACCEPT
  register: allow_vpn

- name: save iptables rules
  shell: iptables-save > /etc/sysconfig/iptables
  when: block_internal_internet.changed or allow_internal.changed or allow_vpn.changed
    
